import type { Metadata } from "next";
import { Faculty_Glyphic, Maven_Pro } from "next/font/google";

import Context from "@/components/Context";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";

const facultyGlyphic = Faculty_Glyphic({
  variable: "--font-faculty-glyphic",
  subsets: ["latin"],
  weight: "400",
});

const mavenPro = Maven_Pro({
  variable: "--font-maven-pro",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${mavenPro.variable} ${facultyGlyphic.variable} antialiased`}
    >
      <body
        className="min-h-screen flex flex-col overflow-x-hidden"
        suppressHydrationWarning
      >
        <Context>
          <Navbar />
          {children}
          <Footer />
        </Context>
      </body>
    </html>
  );
}
