import type { Metadata } from "next";
import { Faculty_Glyphic, Maven_Pro } from "next/font/google";

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";

const facultyGlyphic = Faculty_Glyphic({
  variable: "--font-faculty-glyphic",
  subsets: ["latin"],
  weight: "400",
});

const mavenPro = Maven_Pro({
  variable: "--font-maven-pro",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${mavenPro.variable} ${facultyGlyphic.variable} h-full antialiased`}
    >
      <Navbar />
      <body className=" h-screen flex flex-col">{children}</body>
      <Footer />
    </html>
  );
}
